---
arch: 1
compute_resource: 1
ptable: 55
media: 1
os: 1
host_group: 1
cpus: 1
memory: 512
managed: false
guest_type: 'rhel7_64Guest'
path: '/Datacenters/MYDC/vm/Some Folder/Dev'
cluster: 'MY Cluster 01'
nic_type: 'VirtualE1000'
nic_network: 'VLAN01'
volume_datastore:
  - 'LUN1'
  - 'LUN2'
volume_size: 10
start: 1
